services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cats-n-dogs
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: ~